name: "Coverity"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    container:
      image: fcbrbrazil/coverity:2022.6.0
      credentials:
        username: fcbrbrazil
        password: ${{ secrets.docker_hub_password}}
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
      with:
       swift-version: "5.3.3" 
    - uses: actions/checkout@v3
    
    

    # Perform Static Analysis
    - name: Polaris (SAST)
      run: |
        cov-build --dir idir --fs-capture-search . swift build
        cov-analyze --dir idir --all --webapp-security --enable-audit-mode
