name: "Synopsys Full Scan"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Restore
      run: dotnet restore
      
    # Perform Polaris Analysis
    - name: Polaris (SAST)
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris analyze -w
    # Perform Software Composition Analysis             
    - name: Black Duck (SCA)
      run: |
          bash <(curl -s -L https://detect.synopsys.com/detect7.sh) '--blackduck.url=$BLACKDUCK_URL \
             --blackduck.api.token=$BLACKDUCK_API_TOKEN \
             --detect.project.name=sig-demo/iGoat-Swift \
             --detect.project.version.name=master \
             --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING \
             --detect.blackduck.signature.scanner.upload.source.mode=true'
